a.out :menu.o insert.o print.o sync.o save.o del.o prime.o total.o rev.o
	cc menu.o insert.o print.o sync.o save.o del.o prime.o total.o rev.o
menu.o:menu.c
	cc -c menu.c
insert.o:insert.c
	cc -c insert.c
print.o:print.c
	cc -c print.c
save.o:save.c
	cc -c save.c
sync.o:sync.c
	cc -c sync.c
del.o:del.c
	cc -c del.c
prime.o:prime.c
	cc -c prime.c
total.o:total.c
	cc -c total.c
rev.o:rev.c
	cc -c rev.c
