//defines.h
#define READBIT(WORD,BITPOS)\
				((WORD>>BITPOS)&1)
#define WRITEBIT(WORD,BITPOS,BIT)\
		WORD=((WORD&~(1<<BITPOS))|(BIT<<BITPOS))

#define SETBIT(WORD,BITPOS) (WORD|=1<<BITPOS)
#define SSETBIT(WORD,BITPOS) (WORD=1<<BITPOS)
#define SCLRBIT SSETBIT
#define CLRBIT(WORD,BITPOS) (WORD&=~(1<<BITPOS))
#define CPLBIT(WORD,BITPOS) (WORD^=1<<BITPOS)

#define WRITEBYTE(WORD,BITPOS,BYTE)\
		WORD=((WORD&~(255<<BITPOS))|(BYTE<<BITPOS))
#define WRITENIBBLE(WORD,NIBBLESTARTPOS,NIBBLE)\
		WORD=((WORD&~(15<<NIBBLESTARTPOS)|\
		(NIBBLE<<NIBBLESTARTPOS)))
#define READNIBBLE(WORD,NIBBLESTARTPOS)\
		((WORD>>NIBBLESTARTPOS)&15)

#define READWRITEBIT(WORD,WBIT,RBIT)\
		WORD=(WORD&(~(1<<WBIT)))|(((WORD>>RBIT)&1)<<WBIT)
#define READWRITEBIT2(DWORD,DBIT,SWORD,SBIT)\
		DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
