#include<LPC21xx.h>
main()
{			 /***   IODIR0/1   ***/
	/*//cfg direction of gpio pin as output
	IODIR0|=1<<9;
	//RE-CFG DIRECTION OF GPIO OUTPIN BACK AS INPUT	PIN
	IODIR0&=~(1<<9);
	//TO CFG FEW PARTICULAR PINS AS GPIO OUTPUT PINS
	//IODIR0|=1<<6|1<<3|1<<12
	//TO CFG 4 COTIGUOUS PINS AS GPIO OUTPUT PINS
	IODIR0|=15<<22;
	//TO CFG 8 CONTIGIOUS PINS AS GPIO OUTPUT PINS
	IODIR0|=255<<14;
	//TO CFG OUR REQUIRED PINS AS GPIO OUTPUT PINS
	//IODIR0|=4168<<0; */
	  IODIR0|=0X1048<<0;
	  		/***   IOSET0/1   ***/
	//TO SET A PARTICULAR PIN
	IOSET0=1<<3;
	//TO SET FEW PARTICULAR PINS
	IOSET0=1<<6|1<<9|1<<12;
	IOSET0=0XF<<13;
		/***   IOCLR0/1   ***/
	/*//TO CLEAR A PARTICULAR PIN
	IOCLR0=1<<3;
	//TO CLEAR FEW PARTICULAR PINS
	IOCLR0=1<<6|1<<9|1<<12;
	IOCLR0=0XF<<13;*/
		/***   IOPIN0/1   ***/
	//TO READ STATUS OF PARTICULAR PIN
	//((IOPIN0>>3)&1)
	//TO SET PARTICULAR PIN WITHOUT AFFECTING OTHER PINS
	IOPIN0|=1<<10;
	//TO CLEAR PARTICULAR PIN WITHOUT AFFECTING OTHER PINS
	IOPIN0&=~(1<<12);
	//TO READ 4 CONTIGUOUS PINS
	((IOPIN0>>15)&15)
	//TO READ 8 CONTIGUOUS PINS
	((IOPIN0>>15)&255)
	//WRITE A NIBBLE TO 4 CONTIGIOUS PINS WITHOUT AFFECTING OTHER PINS
	IOPIN0=IOPIN0&~(15<<0)|(0X0F<<0);
	//TO WRITE A BYTE TO 8 CONTIGIOUS PINS WITHOUT AFFECTING OTHER PINS
	IOPIN0=IOPIN0&~(255<<0)|(0XFF<<0);

	while(1);
}
