data:menu.o Print.o Add_First.o Add_Last.o Del_Last.o Del_First.o Del.o Rprint.o Add_Sort.o
	cc menu.o Print.o Add_First.o Add_Last.o Del_Last.o Del_First.o Del.o Rprint.o Add_Sort.o -o data
menu.o:menu.c
	cc -c menu.c
Add_First.o:Add_First.c
	cc -c Add_First.c
Print.o:Print.c
	cc -c Print.c
Add_Last.o:Add_Last.c
	cc -c Add_Last.c
Del_Last.o:Del_Last.c
	cc -c Del_Last.c
Del_First.o:Del_First.c
	cc -c Del_First.c
Del.o:Del.c
	cc -c Del.c
Rprint.o:Rprint.c
	cc -c Rprint.c
Add_Sort.o:Add_Sort.c
	cc -c Add_Sort.c
