a.out :menu.o insert.o print.o sync.o save.o delet.o prime.o total.o nth_node.o Nth_node.o
	cc menu.o insert.o print.o sync.o save.o delet.o prime.o total.o nth_node.o Nth_node.o
menu.o:menu.c
	cc -c menu.c
insert.o:insert.c
	cc -c insert.c
print.o:print.c
	cc -c print.c
save.o:save.c
	cc -c save.c
sync.o:sync.c
	cc -c sync.c
delet.o:delet.c
	cc -c delet.c
prime.o:prime.c
	cc -c prime.c
total.o:total.c
	cc -c total.c
nth_node.o:nth_node.c
	cc -c nth_node.c
Nth_node.o:Nth_node.c
	cc -c Nth_node.c
